version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - revive
    - gosec
  settings:
    gosec:
      severity: medium
      confidence: high