name: Build Application

on:
  push:
    branches:
      - develop
      - feature/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (or replace with your stack)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'  # Change to your Go version

      - name: run tests
        run: |
          go mod tidy
          go test -v ./...

      - name: Build the application
        run: |
          mkdir dist
          go mod tidy
          go build -v -ldflags "-X github.com/joukojo/go-what-did-i-do/cmd.GitCommit=$(git rev-parse HEAD) -X github.com/joukojo/go-what-did-i-do/cmd.GitBranch=$(git rev-parse --abbrev-ref HEAD) -X github.com/joukojo/go-what-did-i-do/cmd.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o dist/what-did-i-do

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Test application customer functionalities
        run: |
          ./dist/what-did-i-do --version
          ./dist/what-did-i-do customers add --name "John Doe"
          ./dist/what-did-i-do customers list