name: Build Application

on:
  push:
    branches:
      - develop
      - feature/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (or replace with your stack)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'  # Change to your Go version

      - name: Build the application
        run: |
          go mod tidy
          go build -v -ldflags "-X main.GitCommit=$(git rev-parse HEAD) -X main.GitBranch=$(git rev-parse --abbrev-ref HEAD) -X main.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o what-did-i-do ./...
